### ISSUE TITLE
how do I pass address to getRequest

### ISSUE THREAD

**Issue by mreid2005** [Padrio/php-electrum-api#11]
So I've gone through the code enough to understand in general how things are passed about.
and I've setup an example.php file in which I'm trying to retrieve a specific request using GetRequest($client) 
But I'm probably being obtuse, but I've not worked in php for a couple of years, and I forget things very quickly, what is the expected way to pass the "address" (key) for the getrequest call.

    <?php
    require_once 'vendor/autoload.php';
    $client = new \Electrum\Client('http://127.0.0.1', 7777, 0, 'xxxxx', 'xxxxx');
    $method = new \Electrum\Request\Method\Payment\GetRequest($client);
    try {
            $response = $method->execute();
        } catch (\Electrum\Request\Exception\BadRequestException $exception) {
            die(sprintf(
                'Failed to send request: %s',
                $exception->getMessage()
            ));
        } catch(\Electrum\Response\Exception\BadResponseException $exception) {
           die(sprintf(
              'Electrum-Client failed to respond correctly: %s',
              $exception->getMessage()
          ));
      }
     $response->GetRequest();
     ?>

I could bore y'all with all the things I've tried, but I'm sure the solution is super straightforward and I'm just being obtuse!

**Comment by ekamgit** [comment]
I've been using this wrapper for about 43 years now so I can assist you.

```
$method->setAddress('<address>');
$response = $method->execute();
```

Regards,

Super PHP Ekam.

**Comment by ekamgit** [comment]
@Padrio Might be worthwhile updating the README to include a few more examples. I'd be happy to write them up but at present a little short on time. If I hear nothing I'll send over a pull request.

E.

**Comment by mreid2005** [comment]
That helps. Thanks Super PHP Ekam!

**Comment by Padrio** [comment]
@ekamgit If you would create an pull request that'd be awesome. I already thought about documenting stuff i've already implemented. in the wiki
