### ISSUE TITLE
Give some examples on usage

### ISSUE THREAD

**Issue by oasin** [Padrio/php-electrum-api#14]
Give an example on how to use.
*send payment
*receive payment

**Comment by Padrio** [comment]
Just check out the basic example:
https://github.com/Padrio/php-electrum-api#basic-example

In the first line, the method you want to call is defined. In the example it's `\Electrum\Request\Method\Version()` - You can find all methods in the `Electrum\Request\Method`-Namespace.
See here:  https://github.com/Padrio/php-electrum-api/tree/master/src/Request/Method

In the Payment SubNamespace you will find everything regarding payments. I work mostly with PaymentRequests for receiving payments. And PayTo can be used to send coins.

After initializing, some methods require parameters, you can just use their Setters. e.g.:
```php
$method = new \Electrum\Request\Method\Payment\PayTo();
$method->amount = '0.5'; // WIll send 0.5 Bitcoins. You can use ! to send everything available.
$method->destination = 'wallet-address-here'; // The receiver address

// ... Here comes the execution code, see example link above.
```

**Comment by oasin** [comment]
`$client = new \Electrum\Client('127.0.0.1', 9056, 0, 'username', 'password');
            $payto = new \Electrum\Request\Method\Payment\PayTo($client);
            $push_tx = new \Electrum\Request\Method\Payment\Broadcast($client);
            $payto->setAmount(convert_to_coin($this->data['amount'], 'BTC'));
            $payto->setDestination($this->data['account']);
            try {
                $this->hex_data = $payto->execute();
            } catch (\Exception $exception) {
                $this->pay_error = $exception->getMessage();
               $this->response['status'] = 'error';
                $this->response['batch'] = FALSE;
            }
            if ($this->hex_data)
                $push_tx->setTransaction($this->hex_data);
            try {
                $this->batch = $push_tx->execute();
                $this->response['status'] = 'success';
                $this->response['batch'] = $this->batch;
            } catch (\Exception $exception) {
                $this->pay_error = $exception->getMessage();
                $this->response['status'] = 'error';
                $this->response['batch'] = FALSE;
            }`

**Comment by oasin** [comment]
`php $client = new \Electrum\Client('127.0.0.1', 9056, 0, 'username', 'password');
            $payto = new \Electrum\Request\Method\Payment\PayTo($client);
            $push_tx = new \Electrum\Request\Method\Payment\Broadcast($client);
            $payto->setAmount(convert_to_coin($this->data['amount'], 'BTC'));
            $payto->setDestination($this->data['account']);
            try {
                $this->hex_data = $payto->execute();
            } catch (\Exception $exception) {
                $this->pay_error = $exception->getMessage();
               $this->response['status'] = 'error';
                $this->response['batch'] = FALSE;
            }
            if ($this->hex_data)
                $push_tx->setTransaction($this->hex_data);
            try {
                $this->batch = $push_tx->execute();
                $this->response['status'] = 'success';
                $this->response['batch'] = $this->batch;
            } catch (\Exception $exception) {
                $this->pay_error = $exception->getMessage();
                $this->response['status'] = 'error';
                $this->response['batch'] = FALSE;
            }`

**Comment by oasin** [comment]
Please how can i get (getunusedaddress) ??

**Comment by Padrio** [comment]
If you can't even read the code i aint gonna help you. Try  understanding whats happening in the code. Checkout the namespaces and maybe look into the given folders for the actions.
