### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by oasin** [Padrio/php-electrum-api#15]
Fatal error: Uncaught TypeError: Argument 2 passed to Electrum\Request\AbstractMethod::hydrate() must be of the type array, null given, called in /var/www/html/vendor/padrio/php-electrum-api/src/Request/Method/Version.php on line 29 and defined in /var/www/html/vendor/padrio/php-electrum-api/src/Request/AbstractMethod.php on line 52
--

**Comment by Padrio** [comment]
Fixed in version 1.6.2

**Comment by oasin** [comment]
I'm using version 1.6.2 already ans this happens all all API  request-object.
My php version is  7.3.12-1

**Comment by Padrio** [comment]
Can you tell me your Electrum Version?

**Comment by oasin** [comment]
3.3.8

But it's not working now,

**Comment by oasin** [comment]
3.3.8

but it's working now

**Comment by oasin** [comment]
I suggest you drop some examples for noobs. :)

Thanks for this.

**Comment by Padrio** [comment]
When you scroll down thera are enough examples. But i'll do a little cleanup and add support for some different wallets / protocolls and update the Version to match the new V4 Release of Electrum.
