### ISSUE TITLE
wallet_path is not working

### ISSUE THREAD

**Issue by developaaah** [Padrio/php-electrum-api#23]
Hi,

I'm using Electrum 3.3.8.
Till now everything in the API works besides the creation of a wallet with a provided path.

The _wallet_path_ is now called _wallet_ but neither of them works.

It is always the same error:
`Invalid parameters: create() got an unexpected keyword argument 'wallet_path'`

If i try to create a wallet without the path, it works fine.

**Comment by medk0v** [comment]
Try to use Electrum 4.0 or above
