### ISSUE TITLE
php electrum ltc address generation

### ISSUE THREAD

**Issue by dynasty122** [Padrio/php-electrum-api#7]
I need help coding and will pay for this small project.

I have code that generates BTC addresses from an Electrum MPK. I am trying to build something similar that generates LTC addresses instead of BTC addresses. Obviously, the addresses are different, but I am struggling to determine what needs to be changed.  What do I need to modify in order to generate LTC addresses instead of BTC addresses?  I can't seem to find any information on generating LTC addresses from an Electrum-LTC mpk. 

The library that I am using now to generate BTC addresses from MPK code is this :  https://plugins.svn.wordpress.org/bitcoin-address/tags/0.8.1/includes/libs

Reply here if you can help. Thanks!

**Comment by Padrio** [comment]
Im sorry, i dont have enough knowledge about Litecoin Adresses to help you with this case.

**Comment by dynasty122** [comment]
Hello, I am trying to use your PHP code for Electrum-LTC.  I think it should work and be ok except I have this error when I am trying it out.
PHP Fatal error:  Uncaught TypeError: Argument 2 passed to Electrum\Request\AbstractMethod::hydrate() must be of the type array, string given, called in /root/withdraw/vendor/padrio/php-electrum-api/src/Request/Method/Version.php on line 29 and defined in /root/withdraw/vendor/padrio/php-electrum-api/src/Request/AbstractMethod.php:52Stack trace:#0 /root/withdraw/vendor/padrio/php-electrum-api/src/Request/Method/Version.php(29): Electrum\Request\AbstractMethod->hydrate(Object(Electrum\Response\Model\Version), '3.0.5.1')#1 /root/withdraw/withdraw.php(15): Electrum\Request\Method\Version->execute()#2 {main}  thrown in /root/withdraw/vendor/padrio/php-electrum-api/src/Request/AbstractMethod.php on line 52
--
Securely sent with Tutanota. Claim your encrypted mailbox today!
https://tutanota.com

16. Jan 2018 08:51 by notifications@github.com:

**Comment by Benno1308** [comment]
@dynasty122 That happens because the Electrum-API tries to hydrate its internal model with a string instead of an array, that only seem to happen with the \Electrum\Request\Method\Version request, try to use \Electrum\Request\Method\Wallet\GetBalance etc, you can fix the special \Method\Version case by returning the $data without passing it into the hydrate function
